# When a PR is opened or a push is made, check code
# for duplication with PHP Copy/Paste Detector.
name: PHPCPD

on:
  pull_request:
    branches:
      - 'develop'
      - '4.*'
    paths:
      - 'app/**.php'
      - 'public/**.php'
      - 'system/**.php'
      - '.github/workflows/test-phpcpd.yml'
  push:
    branches:
      - 'develop'
      - '4.*'
    paths:
      - 'app/**.php'
      - 'public/**.php'
      - 'system/**.php'
      - '.github/workflows/test-phpcpd.yml'

jobs:
  phpcpd:
    uses: codeigniter4/.github/.github/workflows/phpcpd.yml@main
    with:
      dirs: "app/ public/ system/"
      options: >-
        --exclude system/Test
        --exclude system/ThirdParty
        --exclude system/Database/SQLSRV/Builder.php
        --exclude system/Database/SQLSRV/Forge.php
        --exclude system/Database/MySQLi/Builder.php
        --exclude system/Database/OCI8/Builder.php
        --exclude system/Database/Postgre/Builder.php
        --exclude system/Debug/Exceptions.php
        --exclude system/HTTP/SiteURI.php
        --exclude system/Validation/Rules.php
        --exclude system/Autoloader/Autoloader.php
        --exclude system/Config/Filters.php
